
trigger:
- packaging_pipeline

jobs:
  - job: commands_zip
    displayName: "Build commands.zip"
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: yarn install
      displayName: 'Yarn install'
    - script: yarn run package-commands-zip
      displayName: 'Run yarn package-commands-zip'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: 'build_tmp/*.zip'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'output'
        targetPath: '$(Build.ArtifactStagingDirectory)'
